# Generated by Django 3.2.3 on 2021-05-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name_plural': 'Variations'},
        ),
    ]
